# Generated by Django 4.2.9 on 2024-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_about_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="socialMedia",
            field=models.CharField(max_length=200),
        ),
    ]
