# Generated by Django 4.2.9 on 2024-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_about_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="projectType",
            field=models.CharField(
                choices=[("sites", "sites"), ("outros", "outros")], max_length=100
            ),
        ),
    ]
